version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: langgraph
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: langgraph
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  graph:
    build: .
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://langgraph:secretpassword@db:5432/langgraph
      REDIS_URL: redis://redis:6379
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      LANGSMITH_TRACING: "true"
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  db_data:
